### ISSUE TITLE
Entry notification is triggered twice.

### ISSUE THREAD

**Issue by simonmitchell** [martijndeh/react-native-region-monitor#1]
It seems like entry notifications on the JS side are called twice using your current implementation. According to the Apple docs on the `locationManager(_ manager: CLLocationManager, 
            didDetermineState state: CLRegionState, 
                          for region: CLRegion)` function:

https://developer.apple.com/reference/corelocation/cllocationmanagerdelegate/1423570-locationmanager

> The location manager calls this method whenever there is a boundary transition for a region. It calls this method in addition to calling the `locationManager(_:didEnterRegion:)` and `locationManager(_:didExitRegion:)` methods. The location manager also calls this method in response to a call to its `requestState(for:)` method, which runs asynchronously.

Was there any reason that you were sending your region changed event from this method as well as the didEnterRegion? I'm going to submit a pull request to remove the call in this function :)

**Comment by martijndeh** [comment]
Thanks for the pull request @simonmitchell!

I tried to make a JavaScript translation of CLLocationManager which requires less boilerplate in user-land. This means request authorisation is automatically invoked when you add your first region. Another feature is, when adding a region and the user is already inside the region, a region change notification is immediately posted (this doesn't happen out of the box). That's why request state is called in `locationManager:didStartMonitoringForRegion:`.

This likely produces the bug you just fixed. But I want to double check if `locationManager: didDetermineState:forRegion:` is completely unnecessary: does `locationManager:didEnterRegion:` get invoked when requesting a region's state after it was added? Is this something you know? I'll do a quick test now.

**Comment by martijndeh** [comment]
OK, I did a few tests and it looks like `locationManager:didEnterRegion:` is not invoked when checking the state of the region. This makes sense. (There is another issue where the state of the region is sometimes unknown right after adding a new region. So there needs to be some sort of time out or retry).

This does mean the pull request cannot be merged right now. Instead of completely removing the `locationManager:didDetermineState:forRegion:` we should somehow check if the callback was invoked in response to a `requestStateForRegion:` call.

Is this something you want to work on? If not, I'll find some time today or tomorrow to fix this. Please let me know.

**Comment by simonmitchell** [comment]
Hi there, yes I should've read more into it but it does seem you're correct! I won't be able to work on that anytime soon I'm afraid, as it's beyond the scope of what we're using your library for and I can't justify that really with my employer! Otherwise I'd love to take a crack at it :)

**Comment by simonmitchell** [comment]
P.S. Sorry for the delay in response! GitHub didn't send me a notification for your first reply!

**Comment by simonmitchell** [comment]
Is it possible then, that we could rely entirely on `locationManager:didDetermineState:forRegion`?

**Comment by martijndeh** [comment]
Yes good idea. I think just using `locationManager:didDetermineState:forRegion` is possible and the easiest solution!

**Comment by martijndeh** [comment]
I just published some changes in 1.1.1 which should address, among others, this issue. Can you please check and let me know? Thanks!

**Comment by simonmitchell** [comment]
Will take a look at some point today @martijndeh!

**Comment by simonmitchell** [comment]
All looks good to me! Nice work 👍
